# Generated by Django 4.2.1 on 2023-10-22 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spending',
            name='date',
            field=models.DateField(default=datetime.date(2023, 1, 1)),
        ),
    ]
