# Generated by Django 4.2.1 on 2023-06-18 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count', '0002_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participants',
            name='tricount',
        ),
        migrations.AddField(
            model_name='counts',
            name='participants',
            field=models.ManyToManyField(to='count.participants'),
        ),
    ]
