# Generated by Django 4.2.1 on 2023-06-19 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('count', '0003_remove_participants_tricount_counts_participants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participants',
            old_name='participant',
            new_name='name',
        ),
    ]
