# Generated by Django 4.2.1 on 2023-06-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count', '0004_rename_participant_participants_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
